#server:
#  port: 8089

server:
  port: 8089

#spring:
#  application:
#    name: edi-receiver-service
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DB:edirawrequest}
#      database: ${MONGO_DB:edirawrequest}

#spring:
#  application:
#    name: edi-receiver-service
#  data:
#    mongodb:
#      uri: mongodb://${MONGO_HOST:10.0.0.5}:${MONGO_PORT:27017}/${MONGO_DB:edirawrequest}
#      database: ${MONGO_DB:edirawrequest}


spring:
  application:
    name: edi-receiver-service
  data:
    mongodb:
      uri: mongodb://${MONGO_HOST:10.0.0.6}:${MONGO_PORT:27017}/${MONGO_DB:edirawrequest}
      database: ${MONGO_DB:edirawrequest}
######Staging
azure:
  servicebus:
    connection-string: Endpoint=sb://tcxsample.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tivU4T+akUvcHb74Wu4KlPm3f9j85WNYqUYsj2G78NA=
    #    queue-name: tcxqueue
    #    queue-receive-mode: peeklock
    topic-name: edi-raw
    subscription-name: edi-raw
    subscription-receive-mode: peeklock
    allow-telemetry: false

######Production
application:
  appId: 13e64881-bf74-4365-86cd-a1f85053d789
  appName: trimble-cloud-exchange

#azure:
#  servicebus:
#    connection-string: Endpoint=sb://tcxsample.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=tivU4T+akUvcHb74Wu4KlPm3f9j85WNYqUYsj2G78NA=
#    queue-name: tcxqueue
#    queue-receive-mode: peeklock
#    topic-name: raw-event-processing
#    subscription-name: raw-position-event
#    subscription-receive-mode: peeklock
#    allow-telemetry: false
